version: "3.4"
services:

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      environment:
        ADMINER_DESIGN: 'pappu687'

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      links:
        - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mariadb

    mariadb:
      image: mariadb
      restart: always
      volumes:
        - ./phpdocker/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: db
      ports:
        - "8889:3306"
